# This file is used to build the docker containers for the frontend, client, api, proxy, and server.
services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    image: tts-agentifai:client
    container_name: client_container
    networks:
      - tts_network
    environment:
      - PROXY_SERVER_PORT=50051
      - PROXY_SERVER_ADDRESS=proxy_container
    stdin_open: true
    tty: true

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    image: tts-agentifai:frontend
    container_name: frontend_container
    networks:
      - tts_network
    depends_on:
      - api
    environment:
      - REACT_APP_API_PORT=5000
      - PORT=3000
    ports:
      - "3000:3000"

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    image: tts-agentifai:api
    container_name: api_container
    networks:
      - tts_network
    depends_on:
      - proxy
    environment:
      - PROXY_SERVER_ADDRESS=proxy_container
      - PROXY_SERVER_PORT=50051
      - PORT=5000
    ports:
      - "5000:5000"

  proxy:
    build:
      context: .
      dockerfile: docker/Dockerfile.proxy
    image: tts-agentifai:proxy
    container_name: proxy_container
    networks:
      - tts_network
    depends_on:
      - server_1
      - server_2
      - server_3
    environment:
      - PROXY_SERVER_PORT=50051
      - PROXY_SERVER_CONFIG=config/proxy_config.json
    ports:
      - "50051:50051"
    command: ["python", "app_proxy", "-d"]

  normalizer:
    build:
      context: .
      dockerfile: docker/Dockerfile.normalizer
    image: tts-agentifai:normalizer
    container_name: normalizer_container
    networks:
      - tts_network
    environment:
      - NORMALIZER_SERVICE_PORT=50051
      - NORMALIZER_SERVICE_RULES=config/normalization/rules.toml

  server_1:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    image: tts-agentifai:server
    container_name: server_container1
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    depends_on:
      - normalizer
    networks:
      - tts_network
    environment:
      - SERVER_PORT=50051
      - SERVER_CONFIG=config/intlex_config.json
      - NORMALIZER_SERVICE_ADDRESS=normalizer_container
      - NORMALIZER_SERVICE_PORT=50051

  server_2:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    image: tts-agentifai:server
    container_name: server_container2
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    depends_on:
      - normalizer
    networks:
      - tts_network
    environment:
      - SERVER_PORT=50051
      - SERVER_CONFIG=config/intlex_config.json
      - NORMALIZER_SERVICE_ADDRESS=normalizer_container
      - NORMALIZER_SERVICE_PORT=50051

  server_3:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    image: tts-agentifai:server
    container_name: server_container3
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    depends_on:
      - normalizer
    networks:
      - tts_network
    environment:
      - SERVER_PORT=50051
      - SERVER_CONFIG=config/intlex_config.json
      - NORMALIZER_SERVICE_ADDRESS=normalizer_container
      - NORMALIZER_SERVICE_PORT=50051

networks:
  tts_network:
    name: tts_network # Use a static name instead of default directory-based prefix
    driver: bridge
