# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tts_pb2 as tts__pb2


class TTSServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SynthesizeStream = channel.stream_stream(
                '/tts.TTSService/SynthesizeStream',
                request_serializer=tts__pb2.SynthesisRequest.SerializeToString,
                response_deserializer=tts__pb2.SynthesisResponse.FromString,
                )


class TTSServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SynthesizeStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SynthesizeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.SynthesizeStream,
                    request_deserializer=tts__pb2.SynthesisRequest.FromString,
                    response_serializer=tts__pb2.SynthesisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tts.TTSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TTSService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SynthesizeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/tts.TTSService/SynthesizeStream',
            tts__pb2.SynthesisRequest.SerializeToString,
            tts__pb2.SynthesisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
