# config/normalization_rules.toml

rule_order = [
  "date_conversion",
  "number_conversion",
  "abbreviations",
  "custom_replacements",
  "punctuation_handling",
]

supported_languages = ["en", "pt"]

[rules.number_conversion]
enabled = true
amount_aware = true
supported_currency = ["$", "€", "£"]
currency_map = "config/currency_map.json"
regex_map = "config/regex_map.json"
type = "cardinal"

[rules.number_conversion.normalize]
numbers = true
percentage = true
years = false
ordinal = true
fractions = true
ranges = true
currency = true

[rules.date_conversion]
enabled = true
formats = ["yyyy(sep)MM(sep)dd", "dd(sep)MM(sep)yyyy", "MM(sep)dd(sep)yyyy"]
allowed_separator = ["-", "/", ".", " "]
allow_partial_dates = true

[rules.abbreviations]
enabled = true
abbreviation_file = "config/abbreviations.json"

[rules.custom_replacements]
enabled = true
case_sensitive = false
use_regex_flags = true
custom_replacement_file = "config/custom_replacements.json"

[rules.punctuation_handling]
enabled = false
remove = [".", ",", ":", ";", "!", "?", "(", ")", "[", "]", "{", "}", "<", ">", "\"", "'"]
replace_with_space = []
