# Use Python 3.12 slim as the base image
FROM python:3.12-slim

# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
# Default IP, can be overridden at runtime
#ENV SERVER_IP=127.0.0.1  

# Set the working directory in the container
WORKDIR /app

# Copy the client-specific requirements file and install dependencies
COPY ../enviroments/client_requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the entire project directory into the container (adjust to only copy required files)
COPY ../app_client /app/app_client

COPY ../config /app/config

# Copy shared gRPC proto files if needed
COPY ../grpcs/proto /app/proto

COPY ../model /app/model

COPY ../inputs /app/inputs 

# Expose relevant ports (if any; 50051 is common for gRPC)
EXPOSE 50051

# Default command to run the client
CMD ["sh", "-c", "python app_client $SERVER_IP"]