# Use a Python base image
FROM python:3.12-slim

# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV GRPC_PORT 50051
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Lisbon

# Set working directory
WORKDIR /app

# Update apt
RUN apt update  && apt upgrade -y

# Set timezone to Europe/Lisbon (Portugal) and install tzdata
RUN apt -y install tzdata

# Install ffmpeg and wget
RUN apt install -y ffmpeg wget

# Copy the server-specific requirements and install dependencies
COPY enviroments/server_requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy server code
COPY app_server app_server

COPY config config

COPY scripts scripts

COPY db db

# Copy shared gRPC proto files if needed
COPY grpcs grpcs

COPY model model

RUN sh scripts/download_model.sh

COPY inputs inputs

# Expose the gRPC server port
EXPOSE ${GRPC_PORT}

# Set the default command to run the server
CMD ["python", "app_server"]
