# Use a Python base image
FROM python:3.12-slim

# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Lisbon

## Load the environment variables required for the server
ENV SERVER_PORT=50051
ENV SERVER_CONFIG=config/intlex_config.json
ENV NORMALIZER_IPADDRESS=localhost
ENV NORMALIZER_PORT=50051

# Set working directory
WORKDIR /app

# Update apt
RUN apt update  && apt upgrade -y

# Set timezone to Europe/Lisbon (Portugal) and install tzdata
RUN apt -y install tzdata && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime && dpkg-reconfigure --frontend noninteractive tzdata

# Install ffmpeg and wget
RUN apt install -y ffmpeg wget

# Copy server code and required files
COPY app_server app_server
COPY config config
COPY scripts scripts
COPY db db
COPY grpcs grpcs
RUN mkdir model
COPY inputs inputs

# Copy the server-specific requirements and install dependencies
COPY enviroments/server_requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Download the fine-tuned model from the cloud
RUN sh scripts/download_model.sh

# Expose the gRPC server port
EXPOSE ${SERVER_PORT}

# Set the defaukeylt command to run the server
CMD ["python", "app_server"]
