### WIP ###


# Use Python 3.12 slim as the base image
FROM python:3.12-slim

# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV GRPC_PORT 50051
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Lisbon
## This is set in the docker-compose file or when running the container
ENV IPADD=sparrow 

# Set the working directory in the container
WORKDIR /app

# Copy the client-specific requirements file and install dependencies
COPY enviroments/api_requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project directory into the container (adjust to only copy required files)
COPY app_api app_api

COPY app_client app_client

# Copy shared gRPC proto files if needed
COPY grpcs/proto proto

# Expose relevant ports (if any; 50051 is common for gRPC)
EXPOSE ${GRPC_PORT}

# Default command to run the client
CMD ["sh", "-c", "python app_api"]
