# Use Python 3.12 slim as the base image
FROM python:3.12-slim

# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Lisbon

## This is set in the docker-compose file or when running the container
ENV PROXY_ADD=localhost 
ENV PROXY_PORT=50051
ENV PORT=5000

# Set working directory
WORKDIR /app

# Update apt
RUN apt update  && apt upgrade -y

# Set timezone to Europe/Lisbon (Portugal) and install tzdata
RUN apt -y install tzdata && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime && dpkg-reconfigure --frontend noninteractive tzdata

# Copy the entire project directory into the container (adjust to only copy required files)
COPY app_api app_api
COPY app_client app_client
COPY grpcs grpcs

# Copy the client-specific requirements file and install dependencies
COPY enviroments/api_requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose relevant ports if any
EXPOSE ${PORT}

# Default command to run the client
CMD ["python","app_api"]
