# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: normalizer.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'normalizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10normalizer.proto\x12\nnormalizer\" \n\x10NormalizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\",\n\x11NormalizeResponse\x12\x17\n\x0fnormalized_text\x18\x01 \x01(\t2]\n\x11NormalizerService\x12H\n\tNormalize\x12\x1c.normalizer.NormalizeRequest\x1a\x1d.normalizer.NormalizeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'normalizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NORMALIZEREQUEST']._serialized_start=32
  _globals['_NORMALIZEREQUEST']._serialized_end=64
  _globals['_NORMALIZERESPONSE']._serialized_start=66
  _globals['_NORMALIZERESPONSE']._serialized_end=110
  _globals['_NORMALIZERSERVICE']._serialized_start=112
  _globals['_NORMALIZERSERVICE']._serialized_end=205
# @@protoc_insertion_point(module_scope)
