# config/normalization_rules.toml

rule_order = [
  "date_conversion",
  "number_conversion",
  "abbreviations",
  "custom_replacements",
  "punctuation_handling",
]
supported_languages = ["en", "pt"]
detect_language = true

[rules.number_conversion]
enabled = true
detect_percentage = true
detect_years = true
detect_ordinal = true
handle_fractions = true
handle_ranges = true
handle_currency = true
amount_aware = true
supported_currency = ["$", "€", "£"]
currency_map = "config/currency_map.json"
type = "cardinal"

[rules.date_conversion]
enabled = true
formats = ["yyyy(sep)MM(sep)dd", "dd(sep)MM(sep)yyyy", "MM(sep)dd(sep)yyyy"]
allowed_separator = ["-", "/", ".", " "]
allow_partial_dates = true

[rules.abbreviations]
enabled = true
abbreviation_file = "config/abbreviations.json"

[rules.custom_replacements]
enabled = true
case_sensitive = false
use_regex_flags = true
custom_replacement_file = "config/custom_replacements.json"

[rules.punctuation_handling]
enabled = false
remove = []
replace_with_space = []
