# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\x03tts\" \n\x10SynthesisRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"=\n\x11SynthesisResponse\x12\x13\n\x0b\x61udio_chunk\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x05\"6\n\x0e\x41\x64\x64UserRequest\x12\x12\n\nuser_token\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"!\n\x0f\x41\x64\x64UserResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\'\n\x11RemoveUserRequest\x12\x12\n\nuser_token\x18\x01 \x01(\t\"$\n\x12RemoveUserResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\":\n\x0f\x41\x64\x64VoiceRequest\x12\x12\n\nvoice_name\x18\x01 \x01(\t\x12\x13\n\x0b\x61udio_chunk\x18\x02 \x01(\x0c\"\"\n\x10\x41\x64\x64VoiceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"&\n\x12RemoveVoiceRequest\x12\x10\n\x08voice_id\x18\x01 \x01(\x05\"%\n\x13RemoveVoiceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"A\n\x19\x41ssociateUserVoiceRequest\x12\x12\n\nuser_token\x18\x01 \x01(\t\x12\x10\n\x08voice_id\x18\x02 \x01(\x05\",\n\x1a\x41ssociateUserVoiceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"I\n!RemoveUserVoiceAssociationRequest\x12\x12\n\nuser_token\x18\x01 \x01(\t\x12\x10\n\x08voice_id\x18\x02 \x01(\x05\"4\n\"RemoveUserVoiceAssociationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x89\x04\n\nTTSService\x12\x45\n\x10SynthesizeStream\x12\x15.tts.SynthesisRequest\x1a\x16.tts.SynthesisResponse(\x01\x30\x01\x12\x34\n\x07\x41\x64\x64User\x12\x13.tts.AddUserRequest\x1a\x14.tts.AddUserResponse\x12=\n\nRemoveUser\x12\x16.tts.RemoveUserRequest\x1a\x17.tts.RemoveUserResponse\x12\x37\n\x08\x41\x64\x64Voice\x12\x14.tts.AddVoiceRequest\x1a\x15.tts.AddVoiceResponse\x12@\n\x0bRemoveVoice\x12\x17.tts.RemoveVoiceRequest\x1a\x18.tts.RemoveVoiceResponse\x12U\n\x12\x41ssociateUserVoice\x12\x1e.tts.AssociateUserVoiceRequest\x1a\x1f.tts.AssociateUserVoiceResponse\x12m\n\x1aRemoveUserVoiceAssociation\x12&.tts.RemoveUserVoiceAssociationRequest\x1a\'.tts.RemoveUserVoiceAssociationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNTHESISREQUEST']._serialized_start=18
  _globals['_SYNTHESISREQUEST']._serialized_end=50
  _globals['_SYNTHESISRESPONSE']._serialized_start=52
  _globals['_SYNTHESISRESPONSE']._serialized_end=113
  _globals['_ADDUSERREQUEST']._serialized_start=115
  _globals['_ADDUSERREQUEST']._serialized_end=169
  _globals['_ADDUSERRESPONSE']._serialized_start=171
  _globals['_ADDUSERRESPONSE']._serialized_end=204
  _globals['_REMOVEUSERREQUEST']._serialized_start=206
  _globals['_REMOVEUSERREQUEST']._serialized_end=245
  _globals['_REMOVEUSERRESPONSE']._serialized_start=247
  _globals['_REMOVEUSERRESPONSE']._serialized_end=283
  _globals['_ADDVOICEREQUEST']._serialized_start=285
  _globals['_ADDVOICEREQUEST']._serialized_end=343
  _globals['_ADDVOICERESPONSE']._serialized_start=345
  _globals['_ADDVOICERESPONSE']._serialized_end=379
  _globals['_REMOVEVOICEREQUEST']._serialized_start=381
  _globals['_REMOVEVOICEREQUEST']._serialized_end=419
  _globals['_REMOVEVOICERESPONSE']._serialized_start=421
  _globals['_REMOVEVOICERESPONSE']._serialized_end=458
  _globals['_ASSOCIATEUSERVOICEREQUEST']._serialized_start=460
  _globals['_ASSOCIATEUSERVOICEREQUEST']._serialized_end=525
  _globals['_ASSOCIATEUSERVOICERESPONSE']._serialized_start=527
  _globals['_ASSOCIATEUSERVOICERESPONSE']._serialized_end=571
  _globals['_REMOVEUSERVOICEASSOCIATIONREQUEST']._serialized_start=573
  _globals['_REMOVEUSERVOICEASSOCIATIONREQUEST']._serialized_end=646
  _globals['_REMOVEUSERVOICEASSOCIATIONRESPONSE']._serialized_start=648
  _globals['_REMOVEUSERVOICEASSOCIATIONRESPONSE']._serialized_end=700
  _globals['_TTSSERVICE']._serialized_start=703
  _globals['_TTSSERVICE']._serialized_end=1224
# @@protoc_insertion_point(module_scope)
