# config/normalization/normalization_rules.toml

rule_order = ["date_conversion", "number_conversion", "abbreviations", "custom_replacements", "punctuation_handling"]
locale = "pt"

[rules.number_conversion]
enabled = true
detect_percentage = true
detect_years = true
detect_ordinal = true
handle_fractions = true
handle_ranges = true
handle_currency = true
supported_currency = ["$", "€"]
currency_map = "config/normalization/currency_map.json"
type = "cardinal"

[rules.date_conversion]
enabled = true
formats = ["yyyy(sep)MM(sep)dd", "dd(sep)MM(sep)yyyy", "MM(sep)dd(sep)yyyy"]
allowed_separator = ["-", "/", ".", " "]
allow_partial_dates = true

[rules.abbreviations]
enabled = true
abbreviation_file = "config/normalization/abbreviations.json"

[rules.custom_replacements]
enabled = true
custom_replacement_file = "config/normalization/custom_replacements.json"
case_sensitive = false
use_regex_flags = true

[rules.punctuation_handling]
enabled = true
remove = [",",".",";",":","!","?","(",")","[","]","{","}","<",">","\"","'"]
replace_with_space = ["/"]
